### ISSUE TITLE
Error when processing the payment.

### ISSUE THREAD

**Issue by rafaelvzago** [ssorj/skupper-example-patient-portal#2]
## Description

- I was testing this example and when I try to pay one bill, the payment processor throws an error.

## Steps to Reproduce

1. Install Skupper with `skupper init --ingress route --enable-console --enable-flow-collector` in the first namespace. (public)
2. Install Skupper with `skupper init ` in the first namespace (private).
3. Link both sites private -> public
4. Access the console and try to see the addresses

## Expected Behavior

Be able to pay the patient bill. 

## Environment (if relevant)

- Testing example: https://github.com/skupperproject/skupper-example-patient-portal
- Skupper Version site 1 (public): 
```
╰─ skupper version
client version                 1.4.0-rc2
transport version              quay.io/skupper/skupper-router:2.4.0-rc2 (sha256:9f60ac5f31cf)
controller version             quay.io/skupper/service-controller:1.4.0-rc2 (sha256:ee17c8d8eba8)
config-sync version            quay.io/skupper/config-sync:1.4.0-rc2 (sha256:64a2f3235092)
flow-collector version         quay.io/skupper/flow-collector:1.4.0-rc2 (sha256:5d966029f6c7)
```
- Skupper Version site 2 (private): 
```
╰─ skupper version
client version                 1.4.0-rc2
transport version              quay.io/skupper/skupper-router:2.4.0-rc2 (sha256:9f60ac5f31cf)
controller version             quay.io/skupper/service-controller:1.4.0-rc2 (sha256:ee17c8d8eba8)
config-sync version            quay.io/skupper/config-sync:1.4.0-rc2 (sha256:64a2f3235092)
flow-collector version         not-found
```
## Additional Information

```java
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-06-02 16:28:14,239 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2023-06-02 16:28:14,270 INFO  [org.apa.cam.mai.BaseMainSupport] (main) Auto-configuration summary
2023-06-02 16:28:14,271 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.component.braintree.configuration.publicKey=w2j4mtbk9ydktvcv
2023-06-02 16:28:14,271 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.component.braintree.configuration.environment=sandbox
2023-06-02 16:28:14,271 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.component.braintree.configuration.merchantId=thxvgqty3g26fkvw
2023-06-02 16:28:14,271 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.component.braintree.configuration.privateKey=xxxxxx
2023-06-02 16:28:14,358 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup summary (total:1 started:1)
2023-06-02 16:28:14,358 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route1 (rest://get:/api/pay)
2023-06-02 16:28:14,359 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.11.1 (camel-1) started in 58ms (build:0ms init:45ms start:13ms)
2023-06-02 16:28:14,462 INFO  [io.quarkus] (main) payment-processor 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.2.0.Final) started in 0.934s. Listening on: http://0.0.0.0:8080
2023-06-02 16:28:14,462 INFO  [io.quarkus] (main) Profile prod activated. 
2023-06-02 16:28:14,463 INFO  [io.quarkus] (main) Installed features: [camel-attachments, camel-braintree, camel-core, camel-platform-http, camel-rest, cdi, smallrye-context-propagation, vertx, vertx-web]
2023-06-02 16:40:26,503 SEVERE [Braintree] (Camel (camel-1) thread #0 - CamelBraintree) SSL Verification failed. Error message: invalid null LoadStoreParameter
2023-06-02 16:40:26,506 ERROR [org.apa.cam.pro.err.DefaultErrorHandler] (Camel (camel-1) thread #0 - CamelBraintree) Failed delivery for (MessageId: 1D8C1C2F2D7C872-0000000000000000 on ExchangeId: 1D8C1C2F2D7C872-0000000000000000). Exhausted after delivery attempt: 1 caught: org.apache.camel.RuntimeCamelException: Error invoking generate with {}: invalid null LoadStoreParameter

Message History (complete message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[route1            ] [route1            ] [from[platform-http:///api/pay?httpMethodRestrict=GET]                         ] [       149]
	...
[route1            ] [to1               ] [braintree://clientToken/generate                                              ] [         0]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
: org.apache.camel.RuntimeCamelException: Error invoking generate with {}: invalid null LoadStoreParameter
	at org.apache.camel.support.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:530)
	at org.apache.camel.support.component.AbstractApiProducer.doInvokeMethod(AbstractApiProducer.java:121)
	at org.apache.camel.support.component.AbstractApiProducer$1.run(AbstractApiProducer.java:88)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.braintreegateway.exceptions.UnexpectedException: invalid null LoadStoreParameter
	at com.braintreegateway.util.Http.getSSLSocketFactory(Http.java:361)
	at com.braintreegateway.util.Http.httpDo(Http.java:128)
	at com.braintreegateway.util.Http.xmlHttpRequest(Http.java:229)
	at com.braintreegateway.util.Http.post(Http.java:88)
	at com.braintreegateway.ClientTokenGateway.generate(ClientTokenGateway.java:37)
	at com.braintreegateway.ClientTokenGateway.generate(ClientTokenGateway.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.camel.support.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:522)
	... 8 more
Caused by: java.lang.IllegalArgumentException: invalid null LoadStoreParameter
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:821)
	at java.base/java.security.KeyStore.load(KeyStore.java:1513)
	at com.braintreegateway.util.Http.getSSLSocketFactory(Http.java:313)
	... 18 more

2023-06-02 16:40:26,509 WARN  [org.apa.cam.com.pla.htt.ver.VertxPlatformHttpConsumer] (vert.x-eventloop-thread-1) Failed handling platform-http endpoint /api/pay. Caused by: [org.apache.camel.RuntimeCamelException - Error invoking generate with {}: invalid null LoadStoreParameter]: org.apache.camel.RuntimeCamelException: Error invoking generate with {}: invalid null LoadStoreParameter
	at org.apache.camel.support.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:530)
	at org.apache.camel.support.component.AbstractApiProducer.doInvokeMethod(AbstractApiProducer.java:121)
	at org.apache.camel.support.component.AbstractApiProducer$1.run(AbstractApiProducer.java:88)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.braintreegateway.exceptions.UnexpectedException: invalid null LoadStoreParameter
	at com.braintreegateway.util.Http.getSSLSocketFactory(Http.java:361)
	at com.braintreegateway.util.Http.httpDo(Http.java:128)
	at com.braintreegateway.util.Http.xmlHttpRequest(Http.java:229)
	at com.braintreegateway.util.Http.post(Http.java:88)
	at com.braintreegateway.ClientTokenGateway.generate(ClientTokenGateway.java:37)
	at com.braintreegateway.ClientTokenGateway.generate(ClientTokenGateway.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.camel.support.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:522)
	... 8 more
Caused by: java.lang.IllegalArgumentException: invalid null LoadStoreParameter
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:821)
	at java.base/java.security.KeyStore.load(KeyStore.java:1513)
	at com.braintreegateway.util.Http.getSSLSocketFactory(Http.java:313)
	... 18 more

2023-06-02 16:40:26,510 INFO  [io.ver.ext.web.RoutingContext] (vert.x-eventloop-thread-1) RoutingContext failure (500): org.apache.camel.RuntimeCamelException: Error invoking generate with {}: invalid null LoadStoreParameter
	at org.apache.camel.support.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:530)
	at org.apache.camel.support.component.AbstractApiProducer.doInvokeMethod(AbstractApiProducer.java:121)
	at org.apache.camel.support.component.AbstractApiProducer$1.run(AbstractApiProducer.java:88)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.braintreegateway.exceptions.UnexpectedException: invalid null LoadStoreParameter
	at com.braintreegateway.util.Http.getSSLSocketFactory(Http.java:361)
	at com.braintreegateway.util.Http.httpDo(Http.java:128)
	at com.braintreegateway.util.Http.xmlHttpRequest(Http.java:229)
	at com.braintreegateway.util.Http.post(Http.java:88)
	at com.braintreegateway.ClientTokenGateway.generate(ClientTokenGateway.java:37)
	at com.braintreegateway.ClientTokenGateway.generate(ClientTokenGateway.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.camel.support.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:522)
	... 8 more
Caused by: java.lang.IllegalArgumentException: invalid null LoadStoreParameter
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:821)
	at java.base/java.security.KeyStore.load(KeyStore.java:1513)
	at com.braintreegateway.util.Http.getSSLSocketFactory(Http.java:313)
	... 18 more

2023-06-02 16:40:26,514 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /api/pay failed, error id: d38ef855-0fd2-44c1-9c0a-1e4b4998b788-1: org.apache.camel.RuntimeCamelException: Error invoking generate with {}: invalid null LoadStoreParameter
	at org.apache.camel.support.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:530)
	at org.apache.camel.support.component.AbstractApiProducer.doInvokeMethod(AbstractApiProducer.java:121)
	at org.apache.camel.support.component.AbstractApiProducer$1.run(AbstractApiProducer.java:88)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.braintreegateway.exceptions.UnexpectedException: invalid null LoadStoreParameter
	at com.braintreegateway.util.Http.getSSLSocketFactory(Http.java:361)
	at com.braintreegateway.util.Http.httpDo(Http.java:128)
	at com.braintreegateway.util.Http.xmlHttpRequest(Http.java:229)
	at com.braintreegateway.util.Http.post(Http.java:88)
	at com.braintreegateway.ClientTokenGateway.generate(ClientTokenGateway.java:37)
	at com.braintreegateway.ClientTokenGateway.generate(ClientTokenGateway.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.camel.support.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:522)
	... 8 more
Caused by: java.lang.IllegalArgumentException: invalid null LoadStoreParameter
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:821)
	at java.base/java.security.KeyStore.load(KeyStore.java:1513)
	at com.braintreegateway.util.Http.getSSLSocketFactory(Http.java:313)
	... 18 more
```

**Comment by hash-d** [comment]
This happens only on OCP 4 (it does not happen on OCP 3 or Minikube) in my testing, and when it has FIPS enabled.  I have opened #3 to fix it.

**Comment by ssorj** [comment]
I've now changed the payment processor to be a simple Python program.  I tried to update the Quarkus one, since it was on quite an old version, but the platform has changed a lot, and it was time consuming to figure out how to fix it.
